### ISSUE TITLE
Feature request: Wait a specific time with surplus

### ISSUE THREAD

**Issue by danyo2011** [iobroker-community-adapters/ioBroker.kecontact#174]
To avoid the immediate start of charging in pv automatic mode, just because the sun showed up for 5 secs the whole day, there should be a waiting timer to evaluate how reliable the sun is shining and whether it's worthy to start charging.
What do you think about it?

**Comment by Sneak-L8** [comment]
Check is done every 30 seconds. Of course there could be another option to start charging only when surplus is sufficient for more than that time.
But there are already options to stop charging after at least x minutes. So is it really needed? It would just be to have "pessimistic" charging strategy instead of an "optimistic"...

**Comment by Sneak-L8** [comment]
No further comments on this suggestion
