### ISSUE TITLE
Possibility to charge vehicle considering epex spot electricity rates like smartenergy or awattar

### ISSUE THREAD

**Issue by Qlink84** [iobroker-community-adapters/ioBroker.kecontact#346]
It would be nice if kecontact adapter would also take epex spot electricity rates into account while dynamic charging is active.
e.g. 

if electricity rate < xx cent OR photovoltaik > xx Watt -> charge vehicle
if electricity rate > xx cent AND photovoltaic < xx Watt -> stop charging

just to name some examples ...

i'm using https://github.com/HGlab01/ioBroker.apg-info/ adapter to get actual electricity rates and electricity rates for the next day into iobroker, but there are several other adapters which do pretty much the same...

best regards

**Comment by Sneak-L8** [comment]
Thanks for your suggestion. How should the vehicle be scharged if electricity rate is below a certain limit?
Charge with minimum power (6A), charge with maximum power?
I think, this is a special use case. Especially because it's not clear with which current the vehicle should be charged then.
WOuldn't it be easier to define an additional energy meter state? In this state you could save a power value if pricing is below your limit. And you could set a value according to your needs (charge fast/slow).
Would this als o be a solution?

**Comment by Sneak-L8** [comment]
Closed because no response within 2,5 months
